### ISSUE TITLE
Cookie Error

### ISSUE THREAD

**Issue by gixxy22** [doublesecretagency/craft-starratings#25]
Error when using this -> https://plugins.doublesecretagency.com/star-ratings/get-rating-cast-by-a-specific-user/

via a console request, it cant set a cookie due to being console request. Can a condition be added to check for console/web?

I get console usage will be rare.

```

2022-05-25 20:12:49 - error - yii\base\UnknownMethodException
yii\base\UnknownMethodException: Calling unknown method: yii\console\Response::getCookies() in /home/test/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /home/test/vendor/doublesecretagency/craft-starratings/src/services/Rate.php(256): yii\base\Component->__call('getCookies', Array)
#1 /home/test/vendor/doublesecretagency/craft-starratings/src/services/Rate.php(240): doublesecretagency\starratings\services\Rate->saveUserHistoryCookie()
#2 /home/test/vendor/doublesecretagency/craft-starratings/src/services/Rate.php(179): doublesecretagency\starratings\services\Rate->_updateUserHistoryCookie(1295084, NULL, '5')
```

**Comment by lindseydiloreto** [comment]
This is fixed in **v2.3.1**. Thanks for reporting it! 👍
